@echo off
echo Initializing Git...
git init
echo Adding files...
git add .
echo Committing...
git commit -m "feat: premium rebuild of CHEMEDIIT"
echo Adding remote...
git remote add origin "https://github.com/praneetpriyansh009-hash/CHEMEDIIT.git"
echo Setting branch...
git branch -M main
echo Pushing to origin...
git push -u origin main
echo Done.
